### ISSUE TITLE
Slack interactive deployが反応しなくなる。

### ISSUE THREAD

**Issue by h-nago** [metaps/genova#12]
たまにSlack interactive deployが反応しなくなることがあります。
slackからコマンドを打ってもgenovaのログに何も残らないので、接続が切れていると思われます。

slack-ruby-bot-serverの問題？
https://github.com/slack-ruby/slack-ruby-bot-server/issues/30

**Comment by naomichi-y** [comment]
@h-nago 
オフィシャルにマージされてました。一旦クローズします。
https://github.com/slack-ruby/slack-ruby-bot-server/issues/73
