### ISSUE TITLE
FargateタイプのRun-Taskが実行できない

### ISSUE THREAD

**Issue by h-nago** [metaps/genova#122]
FargateタイプのRunTaskをデプロイする際以下のエラーが出る
```
Network Configuration must be provided when networkMode 'awsvpc' is specified.
```

が、タスク定義でnetwork_configurationを設定すると
```
unexpected value at params[:network_configuration]
```

とエラーが出る。

**Comment by naomichi-y** [comment]
https://github.com/metaps/genova/wiki/Deploy-configuration
deploy.yml に `network_configuration` を追加しました。
network modeでawsvpcを利用する場合はsubnetsが最低限必須指定となります。
