### ISSUE TITLE
デプロイ中にデプロイ中タスク一覧のようなメッセージを表示したい

### ISSUE THREAD

**Issue by otsuka-kentaro** [metaps/genova#123]
1. 既にデプロイタスク実行中に追加でデプロイ実行
2. ビルドが複数走ることで速度低下
3. デプロイ作業者がタスク失敗と勘違いして複数デプロイ実行 (もしくは genova コンテナの起動確認をする等)

複数デプロイを実行した際にサーバー負荷により genova の反応が悪くなることがあったので、タスク実行中メッセージが表示されていて、タスク終了とともに消えるなどで、タスク実行されているのがわかると便利かなと思いました。

**Comment by naomichi-y** [comment]
Issueが古いため一旦クローズします。
再要望がある場合はReopenしてください。
