### ISSUE TITLE
他アカウントのECRにpushできない

### ISSUE THREAD

**Issue by koda-h** [metaps/genova#127]
例えば、2つのawsアカウントがあり、アカウント1(111111111111)にあるEC2インスタンスからアカウント2のECSへのデプロイを行おうとした場合、

```
I, [2020-01-30T12:09:19.353290 #1]  INFO -- : Pushed image. {"tag": 111111111111.dkr.ecr.ap-northeast-1.amazonaws.com/ticketpay-web-staging:latest}
I, [2020-01-30T12:09:19.647652 #1]  INFO -- : Pushed image. {"tag": 111111111111.dkr.ecr.ap-northeast-1.amazonaws.com/ticketpay-web-staging:build-20200130-120913}
E, [2020-01-30T12:09:19.695534 #1] ERROR -- : The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.
E, [2020-01-30T12:09:19.696932 #1] ERROR -- : /app/lib/genova/utils/cipher.rb:24:in `rescue in decrypt'
```

アカウント1に対してpush されるように見える。

https://github.com/metaps/genova/blob/develop/lib/genova/ecr/client.rb#L8
にて
Aws::STS::Client.new.get_caller_identity[:account]
でアカウント1のIDを取得しているため？

アカウント1 ではなく アカウント2 に対してpushできるようにしてほしい。

**Comment by naomichi-y** [comment]
@koda-h 
`AWS_ACCOUNT_ID` を指定してください。
https://github.com/metaps/genova/wiki/Environment-configuration
