### ISSUE TITLE
Slack App の oauth v2認証の対応

### ISSUE THREAD

**Issue by koda-h** [metaps/genova#131]
## 要望内容
2020/02/07現在、 Slack App を作成すると oauth v2 でのアプリが作成される。
このアプリで認証しようとすると、 `https://{HOST}/api/v1/slack/auth` へリダイレクトされる際に以下エラーが返ってきてしまう。
```
{"type":"other_error","message":"oauth_authorization_url_mismatch"}
```
oauth v2 に対応して欲しい。

### 補足情報
https://api.slack.com/apps?new_classic_app=1 で oauth v1 でのアプリが作成できる。

**Comment by naomichi-y** [comment]
slackコンテナに接続時、 POST `/api/teams` で落ちてる。

https://github.com/slack-ruby/slack-ruby-bot-server/blob/0b8bbbba45a2b07f35b223b4c18ec86888fc0f49/lib/slack-ruby-bot-server/api/endpoints/teams_endpoint.rb#L43

関連?
https://github.com/howdyai/botkit/issues/1892

**Comment by naomichi-y** [comment]
@koda-h 
https://github.com/slack-ruby/slack-ruby-bot-server/issues/108

**Comment by nkdn** [comment]
DialogflowのIntegrationsでSlackのページを見ると
発行されるOAuth URLとEvents Request URLが変わっています。
Slackの設定ページから新しい形式のURLを設定することでOauthV2モジュールを利用できるようになっていることが確認できました

**Comment by naomichi-y** [comment]
@koda-h 
ひとまずv1での文言・スコープ周りの変更をマニュアルに反映しました。
https://github.com/metaps/genova/wiki/Slack-Interactive-deploy

**Comment by otsuka-kentaro** [comment]
5日前に返信来てた
https://github.com/slack-ruby/slack-ruby-bot-server/issues/108#issuecomment-674438566

**Comment by naomichi-y** [comment]
https://github.com/metaps/genova/issues
