### ISSUE TITLE
run_task 実行時のexit_code nil時の判定

### ISSUE THREAD

**Issue by koda-h** [metaps/genova#148]
## 事象
run task 実行時
exit_codeが nil の場合
https://github.com/metaps/genova/blob/develop/lib/genova/ecs/deployer/run_task/client.rb#L65
にて
>undefined method `zero?' for nil:NilClass
となる

## 対応案
`container[:exit_code].to_i.zero?`
のように判定する

**Comment by naomichi-y** [comment]
exit_code、reason共に入らないケースがあるので判定自体を削除しました。
