### ISSUE TITLE
Slack interactive deploy時に誤字がある

### ISSUE THREAD

**Issue by Paik-yoonsuk** [metaps/genova#20]
Slack interactive deployのサービス選択時、誤字があります。
<img width="509" alt="2019-02-27 14 29 09" src="https://user-images.githubusercontent.com/46431134/53468210-9de74780-3a9c-11e9-9e16-c8500c104ca5.png">

**Comment by naomichi-y** [comment]
@Paik-yoonsuk ありがとうございます!
https://github.com/metaps/genova/commit/d74d49d35bf8f774a3fdd5fa7866cafc0d8686fb
