### ISSUE TITLE
Multiple deployments from Slack may fail with git related errors

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#369]
Slackからそれぞれリポジトリの異なるサービスA、サービスBを同時にデプロイしたとき、以下のようなgit関連のエラーでデプロイが失敗することがある。

* `trying to write ref 'refs/tags/build-xxx' with nonexistent object xxx\n"`
* `output: "fatal: ambiguous argument 'origin/release': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n"`
* `output: "error: pathspec 'xxx' did not match any file(s) known to git`
* `conflicting chdir during another chdir block`

動作を確認したところ、サービスBのデプロイログにサービスAのGitタグが取得されるケースがあった。
Slackデプロイはマルチスレッドで動作しているが、gitライブラリ内部で利用してるメソッド `Dir.chdir` がスレッドセーフでないため、プロセス間で変数が共有され発生した現象と考えられる。

* [Using one repo per thread results in errors](https://github.com/ruby-git/ruby-git/issues/355)
* https://github.com/metaps/genova/blob/develop/lib/autoloads/genova/deploy/transaction.rb#L36

現状、Slackデプロイに関しては「リポジトリが異なる場合」のみ同時デプロイを許容していたが、gitライブラリがスレッドセーフでない以上、「リポジトリが同一の場合」と同じ排他制御を組み込む必要がある。

尚、CLIからのデプロイ操作においてはシングルスレッドで動作するため、`-f` (force) オプションをつけることでこの問題を回避することができる。

**Comment by h-nago** [comment]
Docker APIにtarで固めたファイルとDockerfileを投げるとビルドしてくれるので、githubからtarをダウンロードしてdocker apiに投げてビルドさせるというのも選択肢としてはアリかもしれません。
↓DockerのAPI
https://docs.docker.com/engine/api/v1.43/#tag/Image/operation/ImageBuild

デメリットは、pullでの差分取得よりも転送量が大きくなることです。毎回全体をダウンロードすることになるので。
メリットとしては、同じリポジトリでも同時デプロイが可能なことです。

**Comment by naomichi-y** [comment]
@h-nago 
今のところビルド自体は成功しており、どちらかというとビルド前後で失敗することがあります。
自動デプロイのwebhookが発生した際に最新のdeploy.ymlを取得してデプロイ対象か判定する部分や、デプロイ後のgitタグ付け操作時にエラーが起こります。
ビルド周り全般をforkして実行すれば回避できる気もしますが、同一ホスト上での多重デプロイはリソース消費の懸念もあります。
(以前話してたような、デプロイ単位でコンテナ立ち上げるのが理想ではありますね)

**Comment by naomichi-y** [comment]
git操作周りをgithub apiに置き換えることも恐らく可能だが、githubに依存してしまう (gitlabなどに対応できない)。

**Comment by naomichi-y** [comment]
https://github.com/metaps/genova/pull/381

**Comment by naomichi-y** [comment]
よくよく考えたらトランザクションが甘いだけな気がしてきました。
reopenして再検討します。

**Comment by naomichi-y** [comment]
4.4.1でも同様の問題は再現することができた。

1. Slackでデプロイを実行し、リポジトリを指定
2. もう一度同じ内容を繰り返す
3. 2つめのデプロイで以下のエラーが出る。

> conflicting chdir during another chdir block

```
sidekiq_1  | 2023-12-25T19:01:02.893Z pid=7 tid=1gjb class=Github::RetrieveBranchWorker jid=9cd17538a18b84a6b892bef9 elapsed=7.026 INFO: fail
sidekiq_1  | 2023-12-25T19:01:02.895Z pid=7 tid=1gjb WARN: {"context":"Job raised exception","job":{"retry":false,"queue":"github_retrieve_branch","args":["1703530847.038129"],"class":"Github::RetrieveBranchWorker","jid":"9cd17538a18b84a6b892bef9","retry_for":0,"created_at":1703530855.867468,"enqueued_at":1703530855.8675227},"_config":{"labels":"#<Set: {}>","require":".","environment":"development","concurrency":20,"timeout":25,"poll_interval_average":null,"average_scheduled_poll_interval":5,"on_complex_arguments":"raise","error_handlers":["#<Proc:0x00007f315cfa7bb8 /usr/local/bundle/gems/sidekiq-7.1.3/lib/sidekiq/config.rb:37 (lambda)>","#<Proc:0x00007f3153f24370 /app/config/initializers/sidekiq.rb:3>"],"death_handlers":[],"lifecycle_events":{"startup":[],"quiet":[],"shutdown":[],"heartbeat":[],"beat":["#<Proc:0x00007f315bf5d898 /usr/local/bundle/gems/sidekiq-7.1.3/lib/sidekiq/metrics/tracking.rb:133>"]},"dead_max_jobs":10000,"dead_timeout_in_seconds":15552000,"reloader":"#<Sidekiq::Rails::Reloader @app=Genova::Application>","backtrace_cleaner":"#<Proc:0x00007f3153f8c650 /usr/local/bundle/gems/sidekiq-7.1.3/lib/sidekiq/rails.rb:59 (lambda)>","verbose":false,"pidfile":"./tmp/pids/sidekiq.pid","queues":["ecs_service_provisioning","github_deploy","github_retrieve_branch","github_retrieve_branch_watch","slack_deploy_cluster","slack_deploy_target","slack_deploy_confirm","slack_deploy","slack_deploy_history","slack_command_receive","slack_interaction","workflow_deploy"],"config_file":"config/sidekiq.yml","tag":"app","identity":"17e94dd4531f:7:66869ba36c0e"}}
sidekiq_1  | 2023-12-25T19:01:02.896Z pid=7 tid=1gjb WARN: RuntimeError: conflicting chdir during another chdir block
sidekiq_1  | 2023-12-25T19:01:02.898Z pid=7 tid=1gjb WARN: lib/autoloads/genova/code_manager/git.rb:66:in `origin_branches'
sidekiq_1  | lib/autoloads/genova/slack/block_kit/element_object.rb:95:in `branch_options'
sidekiq_1  | lib/autoloads/genova/slack/interactive/bot.rb:61:in `ask_branch'
sidekiq_1  | app/workers/github/retrieve_branch_worker.rb:15:in `perform'
```

**Comment by naomichi-y** [comment]
Dir.chdirからopen3に変更したバージョンを試したところ、今のところは正常に動作しているように見える。
(上記問題も再現せず)

https://github.com/ruby-git/ruby-git/pull/673
