### ISSUE TITLE
Add option to allow parallel deployments in Slack

### ISSUE THREAD

**Issue by koda-h** [metaps/genova#387]
genova内部で使ってるgitライブラリがスレッドセーフでないために、
slack デプロイ時に別リポジトリの情報が表示されるケースがありその解消バージョンがリリースされたが、
同時デプロイ時に排他制御がかかる形になった。

まれに発生するslack デプロイ時に別リポジトリの情報が表示されるケースを許容し、同時デプロイが行えるようにするオプション(非推奨オプション)を要望します。

**Comment by naomichi-y** [comment]
@koda-h 
gitのスレッドセーフ問題を回避するため、fork版を利用してみました。
検証した限りだと、同時にデプロイした際のエラーが解消されていますので、動作確認をお願いします。

* https://github.com/ruby-git/ruby-git/pull/673
* https://github.com/metaps/genova/pull/389
