### ISSUE TITLE
Add support for retrieving parameters from Secrets Manager/Parameter Store during Docker builds

### ISSUE THREAD

**Issue by koda-h** [metaps/genova#432]
2024/08現在、タスク定義側は以下のようにssm, secret managerが設定可能。
https://github.com/metaps/genova/wiki/Encryption-of-environment-variables

deploy.ymlのビルド時のパラメータはKMSのみ対応している状況。
これもssm, secret managerの設定ができるようになるのを要望します。

86eq31gw6

**Comment by naomichi-y** [comment]
https://github.com/metaps/genova/pull/433
