### ISSUE TITLE
Slackデプロイとコマンドデプロイの挙動が違う

### ISSUE THREAD

**Issue by h-nago** [metaps/genova#55]
Slack: serviceが存在しない場合`Service does not exist. [fido-server]`
コマンド: serviceが存在しない場合作成する

合わせたい。

**Comment by naomichi-y** [comment]
@h-nago 
> serviceが存在しない場合作成する

以前、CLIデプロイ時もサービスの作成APIは外したはずですが、再現しますか?
コード的には同じはず。。
https://github.com/metaps/genova/blob/develop/lib/genova/ecs/client.rb#L38

外した理由としては、「デプロイ権限を持つ開発者が必ずしもサービス作成の権限を持つとは限らない」というものです。
サービスやScheduled Taskは事前にTerraform等で作り、 `lifecycle: ignore_changes` とするのが良いかなと考えてます。
同様の考えで、近いうちにScheduled Taskの作成方法も変更予定です。

https://github.com/naomichi-y/ecs_deployer/issues/25

**Comment by h-nago** [comment]
@naomichi-y 
すみません、以前の状態と勘違いしていました。

**Comment by naomichi-y** [comment]
Scheduled Taskの問題はecs_deployer側で対応するのでこちらクローズします。
