### ISSUE TITLE
NameError uninitialized constant CodeManager

### ISSUE THREAD

**Issue by koda-h** [metaps/genova#90]
slack deploy 時に
@bot_name deploy 
をしたときに画像のエラーが発生。(5回位試みたが毎回同じ事象が起こる)

@bot_name history
ではデプロイ可能で、その後に再度
@bot_name deploy
したところ NameError は発生せず正常にデプロイを行うことができた。

![image](https://user-images.githubusercontent.com/38023109/65744789-704aa580-e134-11e9-9a5d-052222070d4f.png)

**Comment by naomichi-y** [comment]
@koda-h 修正しました。
