### ISSUE TITLE
タグを指定してのデプロイ

### ISSUE THREAD

**Issue by yukki0709** [metaps/genova#91]
タグ付け時点での master ブランチの内容でデプロイしたいです。

最新版だとシステムが稼働しなかったり、申告なバグが含まれている場合、過去のタグの内容でデプロイし、異常稼働を回避するのが目的です。
🙇

**Comment by naomichi-y** [comment]
@yukki0709 
CLIのデプロイコマンドに `--tag {tag name}` オプションを追加しました。
Slackからタグを指定してのデプロイは可能性が低いと考えられるため、一旦クローズします。

**Comment by yukki0709** [comment]
@naomichi-y 
ありがとうございます！
🙇
